// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwkWddfY-Dl71L8WK-RHnZozEOcfUDw-I',
    appId: '1:515728386769:web:958aa6d9cbdbcbe479b3f0',
    messagingSenderId: '515728386769',
    projectId: 'casajoyasf',
    authDomain: 'casajoyasf.firebaseapp.com',
    storageBucket: 'casajoyasf.firebasestorage.app',
    measurementId: 'G-SLSTRZ073L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmSKGy1ElqSEBziF1jxlymPxORal7cjZ8',
    appId: '1:515728386769:android:5875e7eae6b584e679b3f0',
    messagingSenderId: '515728386769',
    projectId: 'casajoyasf',
    storageBucket: 'casajoyasf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmcSC7ik9hdwZWensc6oWy3xJWPamFSNU',
    appId: '1:515728386769:ios:0d1e59ff17f5b2e279b3f0',
    messagingSenderId: '515728386769',
    projectId: 'casajoyasf',
    storageBucket: 'casajoyasf.firebasestorage.app',
    androidClientId: '515728386769-0eg8rk8odmnvfehcduh4khs8std64tst.apps.googleusercontent.com',
    iosClientId: '515728386769-g01377pqd2qoseav4gvopv0s7n3tcb8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.casaJoyas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmcSC7ik9hdwZWensc6oWy3xJWPamFSNU',
    appId: '1:515728386769:ios:0d1e59ff17f5b2e279b3f0',
    messagingSenderId: '515728386769',
    projectId: 'casajoyasf',
    storageBucket: 'casajoyasf.firebasestorage.app',
    androidClientId: '515728386769-0eg8rk8odmnvfehcduh4khs8std64tst.apps.googleusercontent.com',
    iosClientId: '515728386769-g01377pqd2qoseav4gvopv0s7n3tcb8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.casaJoyas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwkWddfY-Dl71L8WK-RHnZozEOcfUDw-I',
    appId: '1:515728386769:web:0dea11f04ccd9c7f79b3f0',
    messagingSenderId: '515728386769',
    projectId: 'casajoyasf',
    authDomain: 'casajoyasf.firebaseapp.com',
    storageBucket: 'casajoyasf.firebasestorage.app',
    measurementId: 'G-785PDMJ70X',
  );

}