// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwkWddfY-Dl71L8WK-RHnZozEOcfUDw-I',
    appId: '1:515728386769:web:ccb180544b4ce57279b3f0',
    messagingSenderId: '515728386769',
    projectId: 'casajoyasf',
    authDomain: 'casajoyasf.firebaseapp.com',
    storageBucket: 'casajoyasf.firebasestorage.app',
    measurementId: 'G-983X4F8HFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmSKGy1ElqSEBziF1jxlymPxORal7cjZ8',
    appId: '1:515728386769:android:048aa8ac054dda5679b3f0',
    messagingSenderId: '515728386769',
    projectId: 'casajoyasf',
    storageBucket: 'casajoyasf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmcSC7ik9hdwZWensc6oWy3xJWPamFSNU',
    appId: '1:515728386769:ios:6309e9e453e0d26d79b3f0',
    messagingSenderId: '515728386769',
    projectId: 'casajoyasf',
    storageBucket: 'casajoyasf.firebasestorage.app',
    iosBundleId: 'com.example.casaJoyas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmcSC7ik9hdwZWensc6oWy3xJWPamFSNU',
    appId: '1:515728386769:ios:6309e9e453e0d26d79b3f0',
    messagingSenderId: '515728386769',
    projectId: 'casajoyasf',
    storageBucket: 'casajoyasf.firebasestorage.app',
    iosBundleId: 'com.example.casaJoyas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwkWddfY-Dl71L8WK-RHnZozEOcfUDw-I',
    appId: '1:515728386769:web:551afe1cb1225a6c79b3f0',
    messagingSenderId: '515728386769',
    projectId: 'casajoyasf',
    authDomain: 'casajoyasf.firebaseapp.com',
    storageBucket: 'casajoyasf.firebasestorage.app',
    measurementId: 'G-2P7C3PTRKL',
  );
}
